spring:
  application:
    name: payment-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/payment_store
    username: root
    password: root
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.yaml
    url: jdbc:mysql://localhost:3306/payment_store
    user: root
    password: root
  security:
    token:
      secret-key: MgtqlZi01l05/3fpeck2ZFwtjeqxrndplJK0acQ4l/pPj+pY5yo+DAGx/24ejx/8Icj+mJXtsCl+xfWVwezzAjmchy5A8VlQmBFmFr3uelw=

server:
  port: 9092

stripe:
  secret-key: sk_test_4eC39HqLyjWDarjtT1zdp7dc
  application-fee: 60

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
