spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/payment_store
    username: root
    password: root
  liquibase:
    change-log: classpath:db.changelog/liquibase-changelog.yaml
    url: jdbc:mysql://localhost:3306/payment_store
    user: root
    password: root

server:
  port: 9092
