server:
  port: 9093

spring:
  application:
    name: user-service
  servlet:
    multipart:
      enabled: true
  data:
    mongodb:
      uri: mongodb+srv://root:root@cluster0.gf4mguw.mongodb.net/?retryWrites=true&w=majority
      database: cluster0
      port: 271017

resilience4j:
  circuitbreaker:
    circuitbreaker-aspect-order: 1
    instances:
      payment-service:
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 4
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 4
        waitDurationInOpenState: 25s
  retry:
    retry-aspect-order: 2
    instances:
      payment-service:
        max-retry-Attempts: 5
        wait-duration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        register-health-indicator: true

payment:
  validation:
    base-url: http://localhost:9092
  # base-url: http://localhost:9000/payment-service

gemini:
  base-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent
  api:
    key:

animal:
  profile:
    base-url: http://localhost:9091/graphql