server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lchen2792/AnimalAdoptionSystemConfig.git
          username: ${CONFIG_REPO_USERNAME}
          password: ${CONFIG_REPO_PASSWORD}
          default-label: main
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
